CREATE DATABASE IF NOT EXISTS ptt;
USE ptt;
CREATE TABLE IF NOT EXISTS gossiping (author_id VARCHAR(100), NOT NULL,author_name VARCHAR(100) NULL, title_name VARCHAR(100) NOT NULL, published_time INT NOT NULL PRIMARY KEY,canonical_url VARCHAR(100) NOT NULL,content_text LONGTEXT );
CREATE USER 'admin'@'%' IDENTIFIED BY '123456';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP ON *.* TO 'admin'@'%';
FLUSH PRIVILEGES;
